### PR TITLE
New Destination Partner - Perkville docs

### PR DESCRIPTION
**Pull request by charholt**
### Proposed changes

- Adding docs to onboard new partner - Perkville

### Merge timing
- ASAP once approved?

### CODE REVIEW

**Comment by markzegarelli** [comment]
Hi @charholt. The last thing we need before we can add this doc is to set the destination status in Partner Portal to either Public Beta, or Public. Once that's set, we'll remake the catalog and merge. Thanks!

**Comment by charholt** [comment]
Hi @markzegarelli!

I have set the destination status to Public Beta. Thanks so much!

**Comment by markzegarelli** [comment]
Thanks @charholt. One more thing we need, in order for this to appear in the docs catalog (maybe the app catalog as well, I'm not sure), is at least one Category value. Can you add this through Partner Portal as well?

**Comment by charholt** [comment]
@markzegarelli I've added the category in partner portal. Thanks!

**Review by markzegarelli — APPROVED** [review]

**Pull request merged**
