### PR TITLE
Update copy in Google Tag Manager article

### PR DESCRIPTION
**Pull request by vanand17**
### Proposed changes

Changing a letter from upper case to lower case based on how the event shows up in the destination.

### Merge timing
<!-- When should this get merged/published?

When approved.

### CODE REVIEW

**Comment by kdaswani** [comment]
@vanand17 Have we confirmed this with a live test? I actually don't see anywhere in the code where we send "Loaded a Page" so want to make sure this is actually all true. https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/google-tag-manager/lib/index.js

Probably happens somewhere else but would love 100% confirmation from a true test if possible. We should also probably update the setting description to lowercase "a" in partner portal as well if so: https://app.segment.com/partner-portal/integration/google-tag-manager/settings

**Review by pwseg — APPROVED** [review]

**Comment by kdaswani** [comment]
@vanand17 following up on my last comment before we merge this in.

> Have we confirmed this with a live test? I actually don't see anywhere in the code where we send "Loaded a Page" so want to make sure this is actually all true. https://github.com/segmentio/analytics.js-integrations/blob/master/integrations/google-tag-manager/lib/index.js
> 
> Probably happens somewhere else but would love 100% confirmation from a true test if possible. We should also probably update the setting description to lowercase "a" in partner portal as well if so: https://app.segment.com/partner-portal/integration/google-tag-manager/settings

**Comment by vanand17** [comment]
Hi Kiara,

I saw this request being approved hence I did not go ahead and run a test
myself. Just to probably clarify, the change that was requested by a
customer was around a spelling error which is currently reading 'Loaded A
Page' and this could be changed to 'Loaded a Page' which a lower case 'a'.
Attaching a screenshot below for your reference.

[image: image.png]
[image: image.png]

Link to the sections of our docs -
https://segment.com/docs/connections/destinations/catalog/google-tag-manager/#tracking-all-pages

https://segment.com/docs/connections/destinations/catalog/google-tag-manager/#settings


Apologies if this was not clear, please let me know if you need any further
clarification :)

**Comment by kdaswani** [comment]
Hi @vanand17 - thanks! I ran a test myself to be 100% sure that is what we send. I see that upon a page call, if tracking all pages, we see "Loaded a Page" in the GTM data layer. Approving this PR given my test. I will update the setting description in partner portal to also lowercase the "a" to match
Screen Shot 2022-08-24 at 10 24 55 AM
.

**Review by kdaswani — APPROVED** [review]

**Comment by vanand17** [comment]
Thanks Kiara.

**Pull request merged**
