### PR TITLE
Update Ripe docs

### PR DESCRIPTION
**Pull request by simpajj**
### Proposed changes

Added new documentation and some more information

### Merge timing
ASAP once approved

### CODE REVIEW

**Comment by markzegarelli** [comment]
Hi @simpajj, can you provide a bit of context on these updates? Docs with the content you've added are meant for our classic destinations, whereas the Ripe destinations use the Actions framework.

I realize there may have been a bit of time where the docs did not populate the metadata properly, but we resolved this earlier this week.

Thanks!

**Comment by simpajj** [comment]
> Hi @simpajj, can you provide a bit of context on these updates? Docs with the content you've added are meant for our classic destinations, whereas the Ripe destinations use the Actions framework.
> 
> I realize there may have been a bit of time where the docs did not populate the metadata properly, but we resolved this earlier this week.
> 
> Thanks!

Hi @markzegarelli, thanks for getting back to me. This is mostly a copy overhaul of the documentation for both of our Actions destinations.

> Docs with the content you've added are meant for our classic destinations, whereas the Ripe destinations use the Actions framework.

My intention was to update the docs for the Actions destinations, but I've probably made some error here. Just so that I understand, is it the title that determines whether the documentation is for a Classic or Actions destination? Slightly confused as we don't have a Classic destination.

Thanks!

**Comment by jdykert** [comment]
@markzegarelli wanted to create some more clarity on our objectives, hopefully this helps:

1. Rename destination naming to better reflect how we talk to our customers about them, the _(Actions)_ label seems superfluous since we don't have any classic integration out and thus have no need to differentiate between the old and the new. You [Segment] also do a great job of pointing out which destinations are action-enabled in your catalog UI. We also did not want to add the _web mode_ label to the web destination since that does not map to (or feels suitable) given how we will display it in the public catalog.

2. Call out the add-on nature of the cloud mode destination. While it's possible to use it as a standalone in theory, to enable the full Ripe feature set you need to enable our web mode destination for a JS source.

3. Help our mutual customers understand the specific calls and how they work with our default/OOB mapping for 
our two actions destination. We still include the Actions info in the docs (first paragraph as well as the last few lines for both destinations).

Would love your input on how to better document the _Actions_ capabilities for both entries!

**Comment by markzegarelli** [comment]
Thanks @simpajj and @jdykert for the context! 

For the name change, please connect with Customer Success if you haven't yet. To be honest, I'm not sure if `(Actions)` is a requirement for destinations that use the Actions framework, but CS should be able to advise. We'll update the name on the article to match what we see in the back end.

For the content, the part I'm unsure about is documenting the JS calls for the supported methods. This is how we've documented classic destinations in the past. For actions though, mappings take place in the UI. Best practice in this case would be to add this content to the action descriptions, so that we can place it in context. For example, we would replace `Identify users in Ripe` [here](https://segment.com/docs/connections/destinations/catalog/actions-ripe-cloud/#identify) with:
```
Segment sends Identify calls to Ripe as `identify` events. Ripe displays these events as `Users` by default. `Identify` event data is augmented with traits. It's important to include email as a trait, as soon as it is known. Ripe will use email to populate User views by default. Ripe supports and follows the [Segment's Identify Spec](https://segment.com/docs/connections/spec/identify/#traits), and recommends using the standardized names for the reserved traits covered there.
```

**Comment by jdykert** [comment]
@markzegarelli we're happy to do it that way instead. Can you share any additional boilerplates that would apply to the other sections?

**Comment by markzegarelli** [comment]
Hi @jdykert, I'm not sure what you mean with regards to boilerplates for other sections. Is the end goal to get information like [this](https://github.com/segmentio/segment-docs/pull/4472/files#diff-1499c23bf926114f6d3df896cef8d740a6656d423ea95b8cec0401083b3537b4R46) into the doc to supplement what is there by default?

**Review by jdykert — APPROVED** [review]
Looks great!

**Comment by markzegarelli** [comment]
@jdykert Thanks. We are working on a cleaner way to get that information into the docs, so it can bet contextually relevant with how the docs for Actions-based destinations are built now. Apologies for the delay, but we think this will make updates much smoother in the future. Please stay tuned.

cc: @joe-ayoub-segment - This is another use case for putting docs notes in the context of actions.

**Pull request closed without merging**
