### PR TITLE
[index.md] screeb documentation

### PR DESCRIPTION
**Pull request by tcgilbert**
### Proposed changes

Copy and formatted the documentation provided by Screeb, for their new integration. 

src/connections/destinations/catalog/screeb/index.md

### Merge timing

ASAP

### Related issues (optional)

N/A

### CODE REVIEW

**Comment by markzegarelli** [comment]
Hi @tcgilbert. Do you know the status of this integration in Partner Portal? I don't see it available in PAPI yet for the catalog.

**Comment by tcgilbert** [comment]
Hi Mark,  just set this to "Private Beta."  Let me know if it needs to be Public Beta to show up in PAPI

**Comment by markzegarelli** [comment]
> Hi @markzegarelli, just set this to "Private Beta." Let me know if it needs to be Public Beta to show up in PAPI

Hi @tcgilbert, yes `PUBLIC_BETA` is the minimum status that is exposed to PAPI.

**Comment by tcgilbert** [comment]
Hi @markzegarelli just updated to "Public Beta." Apologies, still getting a hang of the order of operations for these integrations, thanks!

**Comment by markzegarelli** [comment]
It's all good @tcgilbert, I just updated the catalog and am merging now.

**Review by markzegarelli — APPROVED** [review]

**Pull request merged**
