### PR TITLE
Update destination-functions.md - add details on how to gracefully ha…

### PR DESCRIPTION
**Pull request by samkcrespo**
…ndle func errors

### Proposed changes
Added additional details to the Destination Function Errors and Error Handling section, which details how to ensure a function still runs even when a fetch call fails.

### Merge timing
- ASAP once approved

### CODE REVIEW

**Comment by stayseesong** [comment]
@samkcrespo is there a reason why you want this information in the particular spot you requested? It's currently in the Runtime and dependencies section

**Comment by samkcrespo** [comment]
Thanks for that catch @stayseesong ! I definitely meant to include it in the above section, right before "You can read more about [error handling](https://segment.com/docs/connections/functions/destination-functions/#destination-functions-logs-and-errors) below." ; 
image

I can create a new request and close this one - does that work best?

**Comment by stayseesong** [comment]
no please don't create a new request, I can make the edits

**Comment by samkcrespo** [comment]
sounds good, thanks so much :) Sorry about the hassle!

**Review by stayseesong — APPROVED** [review]

**Pull request merged**
