### PR TITLE
Add `npm` tab to analytics.js docs

### PR DESCRIPTION
**Pull request by silesky**
image

### CODE REVIEW

**Comment by stayseesong** [comment]
@silesky it doesn't make sense to include the NPM tab in the location that you want to add it. Currently those tabs are for adding the Segment snippet. But, what you want to add are complete steps for adding NPM. There's already a link above that says "You can add Segment to your project as an [NPM package](https://www.npmjs.com/package/@segment/snippet). For more information, see the instructions on [GitHub](https://github.com/segmentio/analytics-next#-using-as-an-npm-package)."

**Comment by silesky** [comment]
> @silesky it doesn't make sense to include the NPM tab in the location that you want to add it. Currently those tabs are for adding the Segment snippet. But, what you want to add are complete steps for adding NPM. There's already a link above that says "You can add Segment to your project as an [NPM package](https://www.npmjs.com/package/@segment/snippet). For more information, see the instructions on [GitHub](https://github.com/segmentio/analytics-next#-using-as-an-npm-package)."

My take was that I saw those as general install instructions? I also thought we should better encourage people to use the npm version of the library, as that's the most modern approach and it is quite familiar to developers. It's also quite common to have snippet and npm in tabs, e.g. intercom.io onboarding.

**Comment by stayseesong** [comment]
I see what you're saying, let's schedule a meeting to see if we can find a better way to incorporate npm into the docs

**Comment by stayseesong** [comment]
closing this out as it's related to #5854

**Pull request closed without merging**
