### PR TITLE
Fix appfit slug

### PR DESCRIPTION
**Pull request by forstisabella**
### Proposed changes
Fixed the slug for the appfit destination

### Merge timing
after approval/merge of #6019

### Related issues (optional)
#6019

### CODE REVIEW

**Review by stayseesong — APPROVED** [review]

**Comment by muhammadatifjav** [comment]
Can we please change to "appfit" as the partner has requested that their name be updated everywhere to remove the hyphen?  @forstisabella 
cc @tcgilbert

**Comment by forstisabella** [comment]
hi @muhammadatifjav - the slug has to match what's in the partner portal. If @tcgilbert is able to make the update in the partner portal, I'll be happy to update this PR with the new slug!

**Comment by tcgilbert** [comment]
@forstisabella just opened [this PR](https://github.com/segmentio/segment-docs/pull/6052) to account for both folder name and slug override. LMK if I am missing anything otherwise we can close this one out

**Comment by forstisabella** [comment]
closing this - as PR #6052 will cover everything

**Pull request closed without merging**
