### PR TITLE
sprig action destination documentation

### PR DESCRIPTION
**Pull request by bgila**
Note -- I wasn't completely sure if I was supposed to create the yml file as well -- it seems like it should be possible to generate it from the action definition in the action-destinations repo. But happy to create it if needed!

### Proposed changes

* create documentation for initial Sprig action destination release

### Merge timing
- Ideally, as the Sprig action destination is deployed -- https://github.com/segmentio/action-destinations/pull/373

### CODE REVIEW

**Comment by markzegarelli** [comment]
Hi @bgila. Thanks for the contribution! We actually just merged an update to our Action Destinations docs template, but I will apply those updates to this PR.

To answer your question, there is no need to generate the .yaml file. Our docs site will pull any relevant data directly from the destination.

**Comment by markzegarelli** [comment]
@bgila, also, if possible, can you check the Allow edits from maintainers setting on the Pull Request, as described [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

**Comment by bgila** [comment]
> @bgila, also, if possible, can you check the Allow edits from maintainers setting on the Pull Request, as described [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork)?

hmm, sorry, I don't see how to enable this on this PR, or how to do it for a new one :( maybe i need some sort of permission to be able to change that setting?

Screen Shot 2021-12-10 at 5 17 16 PM

Screen Shot 2021-12-10 at 5 18 38 PM

**Comment by markzegarelli** [comment]
@bgila No worries. I'll merge this into an intermediate branch, and we can make any edits we need to there. I'll tag you in that as well so you can keep eyes on it.

Thanks again for this contribution!

**Pull request merged**
